In [30]:
import pandas as pd
df=pd.read_csv("E:\\Ayu\\CSIT\\VI\\PROJECT-Python\\pokemon.csv")
print(df)

            Name     Type1   Type2   Evolution
0      bulbasaur     Grass  Poison     ivysaur
1        ivysaur     Grass  Poison    venusaur
2       venusaur     Grass  Poison         NaN
3     charmander      Fire     NaN  charmeleon
4     charmeleon      Fire     NaN   charizard
..           ...       ...     ...         ...
804    stakataka      Rock   Steel         NaN
805  blacephalon      Fire   Ghost         NaN
806      zeraora  Electric     NaN         NaN
807       meltan     Steel     NaN         NaN
808     melmetal     Steel     NaN         NaN

[809 rows x 4 columns]

In [ ]:
# df.loc[row,column]
# df.iloc[row_position,column_position]

print(df.loc[0,"Name"])
# 0 : index label
# Name : column name

print(df.iloc[1,0])
# 1 : 2nd row position
# 0 : 1st column position

bulbasaur
ivysaur

In [ ]:
df=pd.DataFrame({
    "Name":["Ram","Shyam","Hari"],
    "Marks":[90,90,90]
}
,index=[100,200,300])
df

      Name  Marks
100    Ram     90
200  Shyam     90
300   Hari     90

In [ ]:
print(df[df['Name']=="fletchinder"])

            Name Type1   Type2 Evolution
661  fletchinder  Fire  Flying       NaN

In [41]:
df[df['Type1']=="Poison"]

          Name   Type1     Type2  Evolution
22       ekans  Poison       NaN      arbok
23       arbok  Poison       NaN        NaN
28   nidoran-f  Poison       NaN   nidorina
29    nidorina  Poison       NaN  nidoqueen
30   nidoqueen  Poison    Ground        NaN
31   nidoran-m  Poison       NaN   nidorino
32    nidorino  Poison       NaN   nidoking
33    nidoking  Poison    Ground        NaN
40       zubat  Poison    Flying        NaN
41      golbat  Poison    Flying        NaN
87      grimer  Poison       NaN        NaN
88         muk  Poison       NaN        NaN
108    koffing  Poison       NaN        NaN
109    weezing  Poison       NaN        NaN
168     crobat  Poison    Flying        NaN
315     gulpin  Poison       NaN        NaN
316     swalot  Poison       NaN        NaN
335    seviper  Poison       NaN        NaN
433     stunky  Poison      Dark        NaN
434   skuntank  Poison      Dark        NaN
450    skorupi  Poison       Bug        NaN
451    drapion  Poison      Dark        NaN
452   croagunk  Poison  Fighting        NaN
453  toxicroak  Poison  Fighting        NaN
567   trubbish  Poison       NaN        NaN
568   garbodor  Poison       NaN        NaN
689     skrelp  Poison     Water        NaN
690   dragalge  Poison    Dragon        NaN
746   mareanie  Poison     Water        NaN
747    toxapex  Poison     Water        NaN
756   salandit  Poison      Fire        NaN
757   salazzle  Poison      Fire        NaN
802    poipole  Poison       NaN        NaN
803  naganadel  Poison    Dragon        NaN

In [ ]:
df[(df["Type1"]=="Dark") & (df["Evolution"]!="NaN") | (df["Name"]=="Poochyena")]

          Name Type1     Type2 Evolution
196    umbreon  Dark       NaN       NaN
197    murkrow  Dark    Flying       NaN
214    sneasel  Dark       Ice       NaN
227   houndour  Dark      Fire       NaN
228   houndoom  Dark      Fire       NaN
260  poochyena  Dark       NaN       NaN
261  mightyena  Dark       NaN       NaN
301    sableye  Dark     Ghost       NaN
358      absol  Dark       NaN       NaN
429  honchkrow  Dark    Flying       NaN
460    weavile  Dark       Ice       NaN
490    darkrai  Dark       NaN       NaN
508   purrloin  Dark       NaN       NaN
509    liepard  Dark       NaN       NaN
558    scraggy  Dark  Fighting       NaN
559    scrafty  Dark  Fighting       NaN
569      zorua  Dark       NaN       NaN
570    zoroark  Dark       NaN       NaN
623   pawniard  Dark     Steel       NaN
624    bisharp  Dark     Steel       NaN
628    vullaby  Dark    Flying       NaN
629  mandibuzz  Dark    Flying       NaN
632      deino  Dark    Dragon       NaN
633   zweilous  Dark    Dragon       NaN
634  hydreigon  Dark    Dragon       NaN
685      inkay  Dark   Psychic       NaN
686    malamar  Dark   Psychic       NaN
716    yveltal  Dark    Flying       NaN
798   guzzlord  Dark    Dragon       NaN

In [64]:
print(df[(df["Type1"]=="Dark") & (df["Type2"]=="Fighting")])

        Name Type1     Type2 Evolution
558  scraggy  Dark  Fighting       NaN
559  scrafty  Dark  Fighting       NaN