# Encoder
- converts string into numerical form

## Types of Encoding:
- Label Encoding : one column becomes numbers
- One-hot Encoding : creates separate columns

### Label Encoding

In [ ]:
import pandas as pd
df=pd.read_csv("../../Datasets/marksheet.csv")

In [2]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Section'] = le.fit_transform(df['Section'])
df

      id      Name  Gender  Age  Section  Science  English  History  Maths
0      1   Bronnie       0   13        2       21       81       62     49
1      2    Lemmie       1   15        1       29       41       17     40
2      3     Danya       0   14        2       12       87       16     96
3      4     Denna       0   14        1       15       53       82     33
4      5   Jocelin       1   14        0       43        6        3     21
..   ...       ...     ...  ...      ...      ...      ...      ...    ...
245  246    Nickie       1   13        2       28       15       25     10
246  247       Rog       0   13        1        1        4       68     65
247  248      Kaia       1   15        1       93       48       82     44
248  249      Anni       0   14        1       35       73       66     59
249  250  Fernande       1   15        1       50        8       80     78

[250 rows x 9 columns]

### One-hot Encoding

In [3]:
df=pd.get_dummies(df,columns=["Gender","Section"],dtype=int)
df

,id,Name,Age,Science,English,History,Maths,Gender_0,Gender_1,Section_0,Section_1,Section_2
0,1,Bronnie,13,21,81,62,49,1,0,0,0,1
1,2,Lemmie,15,29,41,17,40,0,1,0,1,0
2,3,Danya,14,12,87,16,96,1,0,0,0,1
3,4,Denna,14,15,53,82,33,1,0,0,1,0
4,5,Jocelin,14,43,6,3,21,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,13,28,15,25,10,0,1,0,0,1
246,247,Rog,13,1,4,68,65,1,0,0,1,0
247,248,Kaia,15,93,48,82,44,0,1,0,1,0
248,249,Anni,14,35,73,66,59,1,0,0,1,0
249,250,Fernande,15,50,8,80,78,0,1,0,1,0