In [1]:
# default parameter function
def greet(name="Student"):
    print("hello",name)
greet()
greet("Sonny")

hello Student
hello Sonny

In [2]:
# keyword arguments
def info(name,age):
    print(name,age)
info(name="bale",age=20)

bale 20

In [3]:
# lambda function (short function)
add=lambda a,b:a+b
print("Sum = ",add(2,3))

Sum =  5

In [5]:
# variable length arguments
# args(multiple values)
def add(*numbers):
    print(sum(numbers))
add(1,-1,0)

0

In [7]:
# kwargs (key-value pair)
def info(**data):
    print(data)
info(name="Sam",age=15)

{'name': 'Sam', 'age': 15}

In [ ]:
# student result system:
# create a function that:
#     takes marks as input
#     returns "Pass" or "Fail"
subject=dict()

name=input("Enter student name : ")
subject_number=int(input("Enter no. of subjects : "))

for i in range(subject_number):
    
    subject_name=input("Enter subject name : ")
    mark=float(input("Enter marks : "))
    subject[subject_name]=mark

def grade(subject_number,**subject):
    
    percentage=sum(subject.values())/subject_number
    if percentage>=40.00:
        return "Pass"
    else:
        return "Fail"

print(grade(subject_number,**subject))

Fail

In [12]:
# login system (username check)
# System checks if username is correct
# write function that verifies username
username_set={"ayush","byush","cyush","dyush"}
username=input("Enter username : ")

def login(username):
    if username in username_set:
        print("User found : Login succesful")
    else:
        print("User not found : Login failed")
        
login(username)

User not found : Login failed

In [13]:
# file
# file=open(<filename>,<mode>)
# file.close()
# with open(<filename>,<mode>) as file:
    #<operations>
# modes:
    # read->r
    # create->x
    # write->w
    # append->a
try:
    file=open("data.txt","x")
    file.close()
except:
    print("File already created")

In [15]:
file=open("data.txt","r")
data=file.read()
print(data)
file.close()

agagagagagagagaga

In [16]:
file=open("data.txt","w")
file.write("python,java,c++,c#")
file.close()

In [17]:
try:
    file=open("info.csv","x")
    file.close()
except:
    print("File already exists")

In [4]:
import pandas as pd
df=pd.read_csv("pokemon.csv")

In [5]:
df.head()

         Name  Type1   Type2   Evolution
0   bulbasaur  Grass  Poison     ivysaur
1     ivysaur  Grass  Poison    venusaur
2    venusaur  Grass  Poison         NaN
3  charmander   Fire     NaN  charmeleon
4  charmeleon   Fire     NaN   charizard

In [7]:
df.tail(12)

            Name     Type1   Type2 Evolution
797      kartana     Grass   Steel       NaN
798     guzzlord      Dark  Dragon       NaN
799     necrozma   Psychic     NaN       NaN
800     magearna     Steel   Fairy       NaN
801    marshadow  Fighting   Ghost       NaN
802      poipole    Poison     NaN       NaN
803    naganadel    Poison  Dragon       NaN
804    stakataka      Rock   Steel       NaN
805  blacephalon      Fire   Ghost       NaN
806      zeraora  Electric     NaN       NaN
807       meltan     Steel     NaN       NaN
808     melmetal     Steel     NaN       NaN

In [8]:
df=pd.read_csv("pokemon.csv",index_col="Name")

In [ ]:
# expense tracker using function